# Generated by Django 3.2 on 2023-04-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commetn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
